# Generated by Django 5.1.3 on 2025-02-13 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250213_1924'),
    ]

    operations = [
    ]
