# Generated by Django 5.1.3 on 2025-02-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250213_2018'),
    ]

    operations = [
    ]
