version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: avanzatech_blog
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: Secure_password123
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Ajusta la ruta del Dockerfile si es necesario
    container_name: django-backend
    depends_on:
      - db
    environment:
      POSTGRES_DB: avanzatech_blog
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: Secure_password123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_SETTINGS_MODULE: avanzatech_blog.settings  # Configuración de Django
    ports:
      - "8000:8000"  # Puedes cambiar el puerto si es necesario
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "avanzatech_blog.wsgi:application"]  # Ajusta el nombre del archivo WSGI

volumes:
  pg_data:
