# Generated by Django 5.1.3 on 2025-02-13 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20250213_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('READ', 'Read'), ('READ_EDIT', 'Read and Edit'), ('NONE', 'None')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='permissions',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PUBLIC', 'Public'), ('AUTHENTICATED', 'Authenticated'), ('AUTHOR', 'Author'), ('TEAM', 'Team')], max_length=20, unique=True)),
                ('posts', models.ManyToManyField(related_name='category_list', to='posts.blogpost')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_permission', to='posts.permission')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(related_name='blog_posts', to='posts.category'),
        ),
    ]
