# Generated by Django 5.1.3 on 2025-02-13 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_permission_remove_blogpost_permissions_category_and_more'),
    ]

    operations = [
    ]
