# Generated by Django 5.1.3 on 2025-02-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20250213_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='categories',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='authenticated_permission',
            field=models.CharField(choices=[('READ', 'Read'), ('READ_EDIT', 'Read and Edit'), ('NONE', 'None')], default='READ', max_length=15),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_permission',
            field=models.CharField(choices=[('READ', 'Read'), ('READ_EDIT', 'Read and Edit'), ('NONE', 'None')], default='READ_EDIT', max_length=15),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='public_permission',
            field=models.CharField(choices=[('READ', 'Read'), ('READ_EDIT', 'Read and Edit'), ('NONE', 'None')], default='READ', max_length=15),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='team_permission',
            field=models.CharField(choices=[('READ', 'Read'), ('READ_EDIT', 'Read and Edit'), ('NONE', 'None')], default='READ_EDIT', max_length=15),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
