# Generated by Django 5.1.3 on 2025-02-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_category_permission_remove_category_posts_and_more'),
    ]

    operations = [
    ]
