# Generated by Django 5.1.3 on 2025-02-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20250214_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author_permission',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='public_permission',
            field=models.CharField(choices=[('NONE', 'None'), ('READ', 'Read')], default='READ', max_length=10),
        ),
    ]
